### ISSUE TITLE
Errors in montevideo-release branch

### ISSUE THREAD

**Issue by fpacheco** [woodbri/vehicle-routing-problems#23]
Hi, 
We switch to montevideo-release branch and now have several errors (where none existed before). 
The connection to the database is lost even when using vrp_trashCollectionCheck to check the data.

The data:
1 - Containers --->>>>
ruteo=> SELECT
    rc.contenedor AS id, ST_X(rc.geom) AS x, ST_Y(rc.geom) AS y,
    rc.dispinicio AS open, rc.dispfin AS close,
    rc.tiempolevante AS service, rc.peso AS demand, -1 AS street_id
FROM
    ruteocontenedor rc
WHERE
    rc.ruteo=23;
 id  |         x         |         y         | open | close | service | demand | street_id 
------+-------------------+-------------------+------+-------+---------+--------+-----------
 3931 |  -56.198915728334 | -34.8717059827468 |  360 |   840 |     1.6 |    162 |        -1
 3932 |  -56.197278028616 | -34.8673010182977 |  360 |   840 |     1.6 |    216 |        -1
 3933 | -56.2059694348668 | -34.8651835287176 |  360 |   840 |     1.6 |    162 |        -1
 3934 | -56.1979178052941 | -34.8717481669634 |  360 |   840 |     1.6 |    162 |        -1
... more 

2 - Sites --->>>>
ruteo=> SELECT DISTINCT 
    rs.sitio AS id, ST_X(rs.geom) AS x, ST_Y(rs.geom) AS y,  
    rs.abre AS open, rs.cierra AS close  
FROM  
    ruteositio rs  
WHERE
    rs.ruteo=23;  
   id    |        x         |         y         | open | close 
---------+------------------+-------------------+------+-------
 1000004 | -56.129550590685 | -34.8993126047465 |    0 | 14400
 1000009 |        -56.09609 |        -34.849624 |    0 | 14400
(2 rows)

3 -  Vehicles  --->>>>
ruteo=> SELECT
    rv.vehiculo AS vid, rv.sitioinicio AS start_id, rv.sitiodescarga AS dump_id,
    rv.sitioculmina AS end_id, rv.capacidad AS capacity,
    rv.tiempodescarga AS dumpservicetime, rv.dispinicio AS starttime,
    rv.dispfin AS endtime
FROM
    ruteovehiculo rv
WHERE
    rv.ruteo=23;
 vid | start_id | dump_id | end_id  | capacity | dumpservicetime | starttime | endtime 
-----+----------+---------+---------+----------+-----------------+-----------+---------
   1 |  1000004 | 1000009 | 1000004 |     8000 |              10 |       360 |     840
(1 row)

4 - Time matrix for initial solution  --->>>>
ruteo=> SELECT
    r.ndesde AS from_id, r.nhasta AS to_id, r.tiempo AS ttime
FROM
    ruteoosrm r
WHERE
    r.ruteorun=110;

 from_id | to_id |       ttime  
---------+-------+--------------------
     381 |  3942 |                0.5
     381 |  3914 |                1.6
     381 |  3926 |   1.78333333333333
     381 |  3987 |                0.8
     381 |  3904 |   1.33333333333333
     381 |  3905 |                1.1
     381 |  7325 |   1.68333333333333
     381 |  8356 |   1.93333333333333
     381 |  3887 |   1.53333333333333
     381 |  3886 |   1.73333333333333
     381 |  3938 |   1.33333333333333
     381 |  3943 |                0.5
     381 |  3944 |   1.01666666666667
     381 |  3950 |   1.88333333333333
     381 |  3894 |   1.68333333333333
     381 |  3954 |               2.25
     381 |  3901 |  0.983333333333333
... more 

The full output for vrp_trashCollectionCheck ---------->>>>>>>>>>>>>>>
ruteo=> SELECT \*  
FROM
    vrp_trashCollectionCheck('SELECT
    rc.contenedor AS id, ST_X(rc.geom) AS x, ST_Y(rc.geom) AS y,
    rc.dispinicio AS open, rc.dispfin AS close,
    rc.tiempolevante AS service, rc.peso AS demand, -1 AS street_id
FROM
    ruteocontenedor rc
WHERE
    rc.ruteo=23
','SELECT DISTINCT 
    rs.sitio AS id, ST_X(rs.geom) AS x, ST_Y(rs.geom) AS y,
    rs.abre AS open, rs.cierra AS close
FROM
    ruteositio rs
WHERE
    rs.ruteo=23
','SELECT
    rv.vehiculo AS vid, rv.sitioinicio AS start_id, rv.sitiodescarga AS dump_id,
    rv.sitioculmina AS end_id, rv.capacidad AS capacity,
    rv.tiempodescarga AS dumpservicetime, rv.dispinicio AS starttime,
    rv.dispfin AS endtime
FROM
    ruteovehiculo rv
WHERE
    rv.ruteo=23
','SELECT
    r.ndesde AS from_id, r.nhasta AS to_id, r.tiempo AS ttime
FROM
    ruteoosrm r
WHERE
    r.ruteorun=110
');
NOTICE:  Enter solve_trash_collection

NOTICE:  Fetching container tuples

NOTICE:  Fetching otherloc tuples

NOTICE:  Fetching vehicle tuples

NOTICE:  Fetching ttime tuples

NOTICE:  Calling solve_trash_collection_wrapper

NOTICE:  Calling vrp_trash_collection 
SSL SYSCALL error: EOF detected
The connection to the server was lost. Attempting reset: Failed.
!> 

Thank you. Fernando.

**Comment by woodbri** [comment]
I'll look into this but can you ask Emiliano to provide the SQL like in his other reports so we can reproduce the problem here. Or create a schema and create tables for the input data and dump those using `pg_dump -Fp ...` and send that to me.

I ran vrp_trashCollectionCheck() on g_01 test case and it did not crash.

**Comment by etorrano** [comment]
Stephen,

When I run the SQL(pasted at the bottom) for the following scenario(called "Square" by us) we get the following error:

NOTICE:  1 - Actualizando node_distance
NOTICE:  2 - Actualizando node_osrm_data
NOTICE:  Enter route

CONTEXT:  SQL statement "INSERT INTO node_osrm_data(id,osrmdist,osrmtime)
    (SELECT id, tdist, ttime/60.0 FROM osrmint_route('SELECT nd.id AS id, ST_X(nd.geomf) AS xf, ST_Y(nd.geomf) AS yf, ST_X(nd.geomt) AS xt, ST_Y(nd.geomt) AS yt
    FROM
        -- Solo los nodos de esa corrida y entre las other_locs que son pocas (si estuvieran cerca)
        (SELECT *
            FROM
            (
                -- de contenedores a cotenedor y viceversa
                (
                    SELECT n._, g.geom AS geomf, gg.geom as geomt
                    FROM node_distance n, containers c, containers cc, contenedores_geom g, contenedores_geom gg
                    WHERE n.nfrom=c.id AND n.nto=cc.id AND n.nfrom=g.id AND n.nto=gg.id
                )
                UNION
                -- de contenedores (FROM) a other_locs (to)
                (
                    SELECT n._, g.geom AS geomf, o.geom as geomt
                    FROM node_distance n, containers c, contenedores_geom g, other_locs o
                    WHERE n.nfrom=c.id AND n.nto=o.id AND n.nfrom=g.id AND n.nto=o.id
                )
                UNION
                -- de other_locs (FROM) a contenedores (to)
                (
                    SELECT n._, o.geom AS geomf, g.geom as geomt
                    FROM node_distance n, containers c, contenedores_geom g, other_locs o
                    WHERE n.nfrom=o.id AND n.nto=c.id AND n.nfrom=o.id AND n.nto=g.id
                )
                UNION
                -- entre las others_locs
                (
                    SELECT n._, o.geom AS geomf, oo.geom as geomt
                    FROM node_distance n, other_locs o, other_locs oo
                    WHERE n.nfrom=o.id AND n.nto=oo.id
                )
            ) AS d
        ) as nd
    ORDER BY nd.id','http://localhost:5000/viaroute'))"
PL/pgSQL function update_node_osrm_data(text) line 45 at EXECUTE statement
SQL statement "SELECT update_node_osrm_data()"
PL/pgSQL function update_routes(text,text) line 27 at PERFORM
NOTICE:  Fetching datapoint tuples

CONTEXT:  SQL statement "INSERT INTO node_osrm_data(id,osrmdist,osrmtime)
    (SELECT id, tdist, ttime/60.0 FROM osrmint_route('SELECT nd.id AS id, ST_X(nd.geomf) AS xf, ST_Y(nd.geomf) AS yf, ST_X(nd.geomt) AS xt, ST_Y(nd.geomt) AS yt
    FROM
        -- Solo los nodos de esa corrida y entre las other_locs que son pocas (si estuvieran cerca)
        (SELECT *
            FROM
            (
                -- de contenedores a cotenedor y viceversa
                (
                    SELECT n._, g.geom AS geomf, gg.geom as geomt
                    FROM node_distance n, containers c, containers cc, contenedores_geom g, contenedores_geom gg
                    WHERE n.nfrom=c.id AND n.nto=cc.id AND n.nfrom=g.id AND n.nto=gg.id
                )
                UNION
                -- de contenedores (FROM) a other_locs (to)
                (
                    SELECT n._, g.geom AS geomf, o.geom as geomt
                    FROM node_distance n, containers c, contenedores_geom g, other_locs o
                    WHERE n.nfrom=c.id AND n.nto=o.id AND n.nfrom=g.id AND n.nto=o.id
                )
                UNION
                -- de other_locs (FROM) a contenedores (to)
                (
                    SELECT n._, o.geom AS geomf, g.geom as geomt
                    FROM node_distance n, containers c, contenedores_geom g, other_locs o
                    WHERE n.nfrom=o.id AND n.nto=c.id AND n.nfrom=o.id AND n.nto=g.id
                )
                UNION
                -- entre las others_locs
                (
                    SELECT n._, o.geom AS geomf, oo.geom as geomt
                    FROM node_distance n, other_locs o, other_locs oo
                    WHERE n.nfrom=o.id AND n.nto=oo.id
                )
            ) AS d
        ) as nd
    ORDER BY nd.id','http://localhost:5000/viaroute'))"
PL/pgSQL function update_node_osrm_data(text) line 45 at EXECUTE statement
SQL statement "SELECT update_node_osrm_data()"
PL/pgSQL function update_routes(text,text) line 27 at PERFORM
NOTICE:  Calling route

CONTEXT:  SQL statement "INSERT INTO node_osrm_data(id,osrmdist,osrmtime)
    (SELECT id, tdist, ttime/60.0 FROM osrmint_route('SELECT nd.id AS id, ST_X(nd.geomf) AS xf, ST_Y(nd.geomf) AS yf, ST_X(nd.geomt) AS xt, ST_Y(nd.geomt) AS yt
    FROM
        -- Solo los nodos de esa corrida y entre las other_locs que son pocas (si estuvieran cerca)
        (SELECT *
            FROM
            (
                -- de contenedores a cotenedor y viceversa
                (
                    SELECT n._, g.geom AS geomf, gg.geom as geomt
                    FROM node_distance n, containers c, containers cc, contenedores_geom g, contenedores_geom gg
                    WHERE n.nfrom=c.id AND n.nto=cc.id AND n.nfrom=g.id AND n.nto=gg.id
                )
                UNION
                -- de contenedores (FROM) a other_locs (to)
                (
                    SELECT n._, g.geom AS geomf, o.geom as geomt
                    FROM node_distance n, containers c, contenedores_geom g, other_locs o
                    WHERE n.nfrom=c.id AND n.nto=o.id AND n.nfrom=g.id AND n.nto=o.id
                )
                UNION
                -- de other_locs (FROM) a contenedores (to)
                (
                    SELECT n._, o.geom AS geomf, g.geom as geomt
                    FROM node_distance n, containers c, contenedores_geom g, other_locs o
                    WHERE n.nfrom=o.id AND n.nto=c.id AND n.nfrom=o.id AND n.nto=g.id
                )
                UNION
                -- entre las others_locs
                (
                    SELECT n._, o.geom AS geomf, oo.geom as geomt
                    FROM node_distance n, other_locs o, other_locs oo
                    WHERE n.nfrom=o.id AND n.nto=oo.id
                )
            ) AS d
        ) as nd
    ORDER BY nd.id','http://localhost:5000/viaroute'))"
PL/pgSQL function update_node_osrm_data(text) line 45 at EXECUTE statement
SQL statement "SELECT update_node_osrm_data()"
PL/pgSQL function update_routes(text,text) line 27 at PERFORM
NOTICE:  In finish, trying to disconnect from spi 0
CONTEXT:  SQL statement "INSERT INTO node_osrm_data(id,osrmdist,osrmtime)
    (SELECT id, tdist, ttime/60.0 FROM osrmint_route('SELECT nd.id AS id, ST_X(nd.geomf) AS xf, ST_Y(nd.geomf) AS yf, ST_X(nd.geomt) AS xt, ST_Y(nd.geomt) AS yt
    FROM
        -- Solo los nodos de esa corrida y entre las other_locs que son pocas (si estuvieran cerca)
        (SELECT *
            FROM
            (
                -- de contenedores a cotenedor y viceversa
                (
                    SELECT n._, g.geom AS geomf, gg.geom as geomt
                    FROM node_distance n, containers c, containers cc, contenedores_geom g, contenedores_geom gg
                    WHERE n.nfrom=c.id AND n.nto=cc.id AND n.nfrom=g.id AND n.nto=gg.id
                )
                UNION
                -- de contenedores (FROM) a other_locs (to)
                (
                    SELECT n._, g.geom AS geomf, o.geom as geomt
                    FROM node_distance n, containers c, contenedores_geom g, other_locs o
                    WHERE n.nfrom=c.id AND n.nto=o.id AND n.nfrom=g.id AND n.nto=o.id
                )
                UNION
                -- de other_locs (FROM) a contenedores (to)
                (
                    SELECT n._, o.geom AS geomf, g.geom as geomt
                    FROM node_distance n, containers c, contenedores_geom g, other_locs o
                    WHERE n.nfrom=o.id AND n.nto=c.id AND n.nfrom=o.id AND n.nto=g.id
                )
                UNION
                -- entre las others_locs
                (
                    SELECT n._, o.geom AS geomf, oo.geom as geomt
                    FROM node_distance n, other_locs o, other_locs oo
                    WHERE n.nfrom=o.id AND n.nto=oo.id
                )
            ) AS d
        ) as nd
    ORDER BY nd.id','http://localhost:5000/viaroute'))"
PL/pgSQL function update_node_osrm_data(text) line 45 at EXECUTE statement
SQL statement "SELECT update_node_osrm_data()"
PL/pgSQL function update_routes(text,text) line 27 at PERFORM
NOTICE:  In finish, disconnect from spi 0 successfull
CONTEXT:  SQL statement "INSERT INTO node_osrm_data(id,osrmdist,osrmtime)
    (SELECT id, tdist, ttime/60.0 FROM osrmint_route('SELECT nd.id AS id, ST_X(nd.geomf) AS xf, ST_Y(nd.geomf) AS yf, ST_X(nd.geomt) AS xt, ST_Y(nd.geomt) AS yt
    FROM
        -- Solo los nodos de esa corrida y entre las other_locs que son pocas (si estuvieran cerca)
        (SELECT *
            FROM
            (
                -- de contenedores a cotenedor y viceversa
                (
                    SELECT n._, g.geom AS geomf, gg.geom as geomt
                    FROM node_distance n, containers c, containers cc, contenedores_geom g, contenedores_geom gg
                    WHERE n.nfrom=c.id AND n.nto=cc.id AND n.nfrom=g.id AND n.nto=gg.id
                )
                UNION
                -- de contenedores (FROM) a other_locs (to)
                (
                    SELECT n._, g.geom AS geomf, o.geom as geomt
                    FROM node_distance n, containers c, contenedores_geom g, other_locs o
                    WHERE n.nfrom=c.id AND n.nto=o.id AND n.nfrom=g.id AND n.nto=o.id
                )
                UNION
                -- de other_locs (FROM) a contenedores (to)
                (
                    SELECT n._, o.geom AS geomf, g.geom as geomt
                    FROM node_distance n, containers c, contenedores_geom g, other_locs o
                    WHERE n.nfrom=o.id AND n.nto=c.id AND n.nfrom=o.id AND n.nto=g.id
                )
                UNION
                -- entre las others_locs
                (
                    SELECT n._, o.geom AS geomf, oo.geom as geomt
                    FROM node_distance n, other_locs o, other_locs oo
                    WHERE n.nfrom=o.id AND n.nto=oo.id
                )
            ) AS d
        ) as nd
    ORDER BY nd.id','http://localhost:5000/viaroute'))"
PL/pgSQL function update_node_osrm_data(text) line 45 at EXECUTE statement
SQL statement "SELECT update_node_osrm_data()"
PL/pgSQL function update_routes(text,text) line 27 at PERFORM
NOTICE:  Search routes returned status 0
CONTEXT:  SQL statement "INSERT INTO node_osrm_data(id,osrmdist,osrmtime)
    (SELECT id, tdist, ttime/60.0 FROM osrmint_route('SELECT nd.id AS id, ST_X(nd.geomf) AS xf, ST_Y(nd.geomf) AS yf, ST_X(nd.geomt) AS xt, ST_Y(nd.geomt) AS yt
    FROM
        -- Solo los nodos de esa corrida y entre las other_locs que son pocas (si estuvieran cerca)
        (SELECT *
            FROM
            (
                -- de contenedores a cotenedor y viceversa
                (
                    SELECT n._, g.geom AS geomf, gg.geom as geomt
                    FROM node_distance n, containers c, containers cc, contenedores_geom g, contenedores_geom gg
                    WHERE n.nfrom=c.id AND n.nto=cc.id AND n.nfrom=g.id AND n.nto=gg.id
                )
                UNION
                -- de contenedores (FROM) a other_locs (to)
                (
                    SELECT n._, g.geom AS geomf, o.geom as geomt
                    FROM node_distance n, containers c, contenedores_geom g, other_locs o
                    WHERE n.nfrom=c.id AND n.nto=o.id AND n.nfrom=g.id AND n.nto=o.id
                )
                UNION
                -- de other_locs (FROM) a contenedores (to)
                (
                    SELECT n._, o.geom AS geomf, g.geom as geomt
                    FROM node_distance n, containers c, contenedores_geom g, other_locs o
                    WHERE n.nfrom=o.id AND n.nto=c.id AND n.nfrom=o.id AND n.nto=g.id
                )
                UNION
                -- entre las others_locs
                (
                    SELECT n._, o.geom AS geomf, oo.geom as geomt
                    FROM node_distance n, other_locs o, other_locs oo
                    WHERE n.nfrom=o.id AND n.nto=oo.id
                )
            ) AS d
        ) as nd
    ORDER BY nd.id','http://localhost:5000/viaroute'))"
PL/pgSQL function update_node_osrm_data(text) line 45 at EXECUTE statement
SQL statement "SELECT update_node_osrm_data()"
PL/pgSQL function update_routes(text,text) line 27 at PERFORM
NOTICE:  ret=0
CONTEXT:  SQL statement "INSERT INTO node_osrm_data(id,osrmdist,osrmtime)
    (SELECT id, tdist, ttime/60.0 FROM osrmint_route('SELECT nd.id AS id, ST_X(nd.geomf) AS xf, ST_Y(nd.geomf) AS yf, ST_X(nd.geomt) AS xt, ST_Y(nd.geomt) AS yt
    FROM
        -- Solo los nodos de esa corrida y entre las other_locs que son pocas (si estuvieran cerca)
        (SELECT *
            FROM
            (
                -- de contenedores a cotenedor y viceversa
                (
                    SELECT n._, g.geom AS geomf, gg.geom as geomt
                    FROM node_distance n, containers c, containers cc, contenedores_geom g, contenedores_geom gg
                    WHERE n.nfrom=c.id AND n.nto=cc.id AND n.nfrom=g.id AND n.nto=gg.id
                )
                UNION
                -- de contenedores (FROM) a other_locs (to)
                (
                    SELECT n._, g.geom AS geomf, o.geom as geomt
                    FROM node_distance n, containers c, contenedores_geom g, other_locs o
                    WHERE n.nfrom=c.id AND n.nto=o.id AND n.nfrom=g.id AND n.nto=o.id
                )
                UNION
                -- de other_locs (FROM) a contenedores (to)
                (
                    SELECT n._, o.geom AS geomf, g.geom as geomt
                    FROM node_distance n, containers c, contenedores_geom g, other_locs o
                    WHERE n.nfrom=o.id AND n.nto=c.id AND n.nfrom=o.id AND n.nto=g.id
                )
                UNION
                -- entre las others_locs
                (
                    SELECT n._, o.geom AS geomf, oo.geom as geomt
                    FROM node_distance n, other_locs o, other_locs oo
                    WHERE n.nfrom=o.id AND n.nto=oo.id
                )
            ) AS d
        ) as nd
    ORDER BY nd.id','http://localhost:5000/viaroute'))"
PL/pgSQL function update_node_osrm_data(text) line 45 at EXECUTE statement
SQL statement "SELECT update_node_osrm_data()"
PL/pgSQL function update_routes(text,text) line 27 at PERFORM
NOTICE:  Going to free path
CONTEXT:  SQL statement "INSERT INTO node_osrm_data(id,osrmdist,osrmtime)
    (SELECT id, tdist, ttime/60.0 FROM osrmint_route('SELECT nd.id AS id, ST_X(nd.geomf) AS xf, ST_Y(nd.geomf) AS yf, ST_X(nd.geomt) AS xt, ST_Y(nd.geomt) AS yt
    FROM
        -- Solo los nodos de esa corrida y entre las other_locs que son pocas (si estuvieran cerca)
        (SELECT *
            FROM
            (
                -- de contenedores a cotenedor y viceversa
                (
                    SELECT n._, g.geom AS geomf, gg.geom as geomt
                    FROM node_distance n, containers c, containers cc, contenedores_geom g, contenedores_geom gg
                    WHERE n.nfrom=c.id AND n.nto=cc.id AND n.nfrom=g.id AND n.nto=gg.id
                )
                UNION
                -- de contenedores (FROM) a other_locs (to)
                (
                    SELECT n._, g.geom AS geomf, o.geom as geomt
                    FROM node_distance n, containers c, contenedores_geom g, other_locs o
                    WHERE n.nfrom=c.id AND n.nto=o.id AND n.nfrom=g.id AND n.nto=o.id
                )
                UNION
                -- de other_locs (FROM) a contenedores (to)
                (
                    SELECT n._, o.geom AS geomf, g.geom as geomt
                    FROM node_distance n, containers c, contenedores_geom g, other_locs o
                    WHERE n.nfrom=o.id AND n.nto=c.id AND n.nfrom=o.id AND n.nto=g.id
                )
                UNION
                -- entre las others_locs
                (
                    SELECT n._, o.geom AS geomf, oo.geom as geomt
                    FROM node_distance n, other_locs o, other_locs oo
                    WHERE n.nfrom=o.id AND n.nto=oo.id
                )
            ) AS d
        ) as nd
    ORDER BY nd.id','http://localhost:5000/viaroute'))"
PL/pgSQL function update_node_osrm_data(text) line 45 at EXECUTE statement
SQL statement "SELECT update_node_osrm_data()"
PL/pgSQL function update_routes(text,text) line 27 at PERFORM
NOTICE:  3 - Ejecutando vrp_trashCollection
NOTICE:  iteration: 1000
CONTEXT:  SQL statement "INSERT INTO route_vrptools(routeid, seq, vehicle_id, node_id, node_type, delta_time, cargo)
    (
        SELECT 148, *
        FROM vrp_trashCollection('select id, x, y, open, close, service, demand, street_id from containers', 'select id, x, y, tw_open as open, tw_close as close from other_locs', 'select vid, start_id, dump_id, end_id, cast(capacity as float), cast(dump_service_time as float) as dumpservicetime, tw_open as starttime, tw_close as endtime from vehicles', 'select nfrom AS from_id, nto AS to_id, osrmtime AS ttime from node_osrm_data')
    )"
PL/pgSQL function update_routes(text,text) line 38 at EXECUTE statement
NOTICE:  Enter solve_trash_collection

CONTEXT:  SQL statement "INSERT INTO route_vrptools(routeid, seq, vehicle_id, node_id, node_type, delta_time, cargo)
    (
        SELECT 148, *
        FROM vrp_trashCollection('select id, x, y, open, close, service, demand, street_id from containers', 'select id, x, y, tw_open as open, tw_close as close from other_locs', 'select vid, start_id, dump_id, end_id, cast(capacity as float), cast(dump_service_time as float) as dumpservicetime, tw_open as starttime, tw_close as endtime from vehicles', 'select nfrom AS from_id, nto AS to_id, osrmtime AS ttime from node_osrm_data')
    )"
PL/pgSQL function update_routes(text,text) line 38 at EXECUTE statement
NOTICE:  Fetching container tuples

CONTEXT:  SQL statement "INSERT INTO route_vrptools(routeid, seq, vehicle_id, node_id, node_type, delta_time, cargo)
    (
        SELECT 148, *
        FROM vrp_trashCollection('select id, x, y, open, close, service, demand, street_id from containers', 'select id, x, y, tw_open as open, tw_close as close from other_locs', 'select vid, start_id, dump_id, end_id, cast(capacity as float), cast(dump_service_time as float) as dumpservicetime, tw_open as starttime, tw_close as endtime from vehicles', 'select nfrom AS from_id, nto AS to_id, osrmtime AS ttime from node_osrm_data')
    )"
PL/pgSQL function update_routes(text,text) line 38 at EXECUTE statement
NOTICE:  Fetching otherloc tuples

CONTEXT:  SQL statement "INSERT INTO route_vrptools(routeid, seq, vehicle_id, node_id, node_type, delta_time, cargo)
    (
        SELECT 148, *
        FROM vrp_trashCollection('select id, x, y, open, close, service, demand, street_id from containers', 'select id, x, y, tw_open as open, tw_close as close from other_locs', 'select vid, start_id, dump_id, end_id, cast(capacity as float), cast(dump_service_time as float) as dumpservicetime, tw_open as starttime, tw_close as endtime from vehicles', 'select nfrom AS from_id, nto AS to_id, osrmtime AS ttime from node_osrm_data')
    )"
PL/pgSQL function update_routes(text,text) line 38 at EXECUTE statement
NOTICE:  Fetching vehicle tuples

CONTEXT:  SQL statement "INSERT INTO route_vrptools(routeid, seq, vehicle_id, node_id, node_type, delta_time, cargo)
    (
        SELECT 148, *
        FROM vrp_trashCollection('select id, x, y, open, close, service, demand, street_id from containers', 'select id, x, y, tw_open as open, tw_close as close from other_locs', 'select vid, start_id, dump_id, end_id, cast(capacity as float), cast(dump_service_time as float) as dumpservicetime, tw_open as starttime, tw_close as endtime from vehicles', 'select nfrom AS from_id, nto AS to_id, osrmtime AS ttime from node_osrm_data')
    )"
PL/pgSQL function update_routes(text,text) line 38 at EXECUTE statement
NOTICE:  Fetching ttime tuples

CONTEXT:  SQL statement "INSERT INTO route_vrptools(routeid, seq, vehicle_id, node_id, node_type, delta_time, cargo)
    (
        SELECT 148, *
        FROM vrp_trashCollection('select id, x, y, open, close, service, demand, street_id from containers', 'select id, x, y, tw_open as open, tw_close as close from other_locs', 'select vid, start_id, dump_id, end_id, cast(capacity as float), cast(dump_service_time as float) as dumpservicetime, tw_open as starttime, tw_close as endtime from vehicles', 'select nfrom AS from_id, nto AS to_id, osrmtime AS ttime from node_osrm_data')
    )"
PL/pgSQL function update_routes(text,text) line 38 at EXECUTE statement
NOTICE:  Calling solve_trash_collection_wrapper

CONTEXT:  SQL statement "INSERT INTO route_vrptools(routeid, seq, vehicle_id, node_id, node_type, delta_time, cargo)
    (
        SELECT 148, *
        FROM vrp_trashCollection('select id, x, y, open, close, service, demand, street_id from containers', 'select id, x, y, tw_open as open, tw_close as close from other_locs', 'select vid, start_id, dump_id, end_id, cast(capacity as float), cast(dump_service_time as float) as dumpservicetime, tw_open as starttime, tw_close as endtime from vehicles', 'select nfrom AS from_id, nto AS to_id, osrmtime AS ttime from node_osrm_data')
    )"
PL/pgSQL function update_routes(text,text) line 38 at EXECUTE statement
NOTICE:  Calling vrp_trash_collection 
CONTEXT:  SQL statement "INSERT INTO route_vrptools(routeid, seq, vehicle_id, node_id, node_type, delta_time, cargo)
    (
        SELECT 148, *
        FROM vrp_trashCollection('select id, x, y, open, close, service, demand, street_id from containers', 'select id, x, y, tw_open as open, tw_close as close from other_locs', 'select vid, start_id, dump_id, end_id, cast(capacity as float), cast(dump_service_time as float) as dumpservicetime, tw_open as starttime, tw_close as endtime from vehicles', 'select nfrom AS from_id, nto AS to_id, osrmtime AS ttime from node_osrm_data')
    )"
PL/pgSQL function update_routes(text,text) line 38 at EXECUTE statement
NOTICE:  vrp_trash_collection returned status: -1
CONTEXT:  SQL statement "INSERT INTO route_vrptools(routeid, seq, vehicle_id, node_id, node_type, delta_time, cargo)
    (
        SELECT 148, *
        FROM vrp_trashCollection('select id, x, y, open, close, service, demand, street_id from containers', 'select id, x, y, tw_open as open, tw_close as close from other_locs', 'select vid, start_id, dump_id, end_id, cast(capacity as float), cast(dump_service_time as float) as dumpservicetime, tw_open as starttime, tw_close as endtime from vehicles', 'select nfrom AS from_id, nto AS to_id, osrmtime AS ttime from node_osrm_data')
    )"
PL/pgSQL function update_routes(text,text) line 38 at EXECUTE statement
NOTICE:  result_count = 0
CONTEXT:  SQL statement "INSERT INTO route_vrptools(routeid, seq, vehicle_id, node_id, node_type, delta_time, cargo)
    (
        SELECT 148, *
        FROM vrp_trashCollection('select id, x, y, open, close, service, demand, street_id from containers', 'select id, x, y, tw_open as open, tw_close as close from other_locs', 'select vid, start_id, dump_id, end_id, cast(capacity as float), cast(dump_service_time as float) as dumpservicetime, tw_open as starttime, tw_close as endtime from vehicles', 'select nfrom AS from_id, nto AS to_id, osrmtime AS ttime from node_osrm_data')
    )"
PL/pgSQL function update_routes(text,text) line 38 at EXECUTE statement
NOTICE:  Message received from inside:
CONTEXT:  SQL statement "INSERT INTO route_vrptools(routeid, seq, vehicle_id, node_id, node_type, delta_time, cargo)
    (
        SELECT 148, *
        FROM vrp_trashCollection('select id, x, y, open, close, service, demand, street_id from containers', 'select id, x, y, tw_open as open, tw_close as close from other_locs', 'select vid, start_id, dump_id, end_id, cast(capacity as float), cast(dump_service_time as float) as dumpservicetime, tw_open as starttime, tw_close as endtime from vehicles', 'select nfrom AS from_id, nto AS to_id, osrmtime AS ttime from node_osrm_data')
    )"
PL/pgSQL function update_routes(text,text) line 38 at EXECUTE statement
NOTICE:  AssertFailedException: path.size() > 1 at ../solverTrash/tripVehicle.cpp:575
CONTEXT:  SQL statement "INSERT INTO route_vrptools(routeid, seq, vehicle_id, node_id, node_type, delta_time, cargo)
    (
        SELECT 148, *
        FROM vrp_trashCollection('select id, x, y, open, close, service, demand, street_id from containers', 'select id, x, y, tw_open as open, tw_close as close from other_locs', 'select vid, start_id, dump_id, end_id, cast(capacity as float), cast(dump_service_time as float) as dumpservicetime, tw_open as starttime, tw_close as endtime from vehicles', 'select nfrom AS from_id, nto AS to_id, osrmtime AS ttime from node_osrm_data')
    )"
PL/pgSQL function update_routes(text,text) line 38 at EXECUTE statement

ERROR:  Error computing solution: AssertFailedException: path.size() > 1 at ../solverTrash/tripVehicle.cpp:575:

CONTEXT:  SQL statement "INSERT INTO route_vrptools(routeid, seq, vehicle_id, node_id, node_type, delta_time, cargo)
    (
        SELECT 148, *
        FROM vrp_trashCollection('select id, x, y, open, close, service, demand, street_id from containers', 'select id, x, y, tw_open as open, tw_close as close from other_locs', 'select vid, start_id, dump_id, end_id, cast(capacity as float), cast(dump_service_time as float) as dumpservicetime, tw_open as starttime, tw_close as endtime from vehicles', 'select nfrom AS from_id, nto AS to_id, osrmtime AS ttime from node_osrm_data')
    )"
PL/pgSQL function update_routes(text,text) line 38 at EXECUTE statement
*********\* Error **********

ERROR: Error computing solution: AssertFailedException: path.size() > 1 at ../solverTrash/tripVehicle.cpp:575:
SQL state: 38001
Context: SQL statement "INSERT INTO route_vrptools(routeid, seq, vehicle_id, node_id, node_type, delta_time, cargo)
    (
        SELECT 148, *
        FROM vrp_trashCollection('select id, x, y, open, close, service, demand, street_id from containers', 'select id, x, y, tw_open as open, tw_close as close from other_locs', 'select vid, start_id, dump_id, end_id, cast(capacity as float), cast(dump_service_time as float) as dumpservicetime, tw_open as starttime, tw_close as endtime from vehicles', 'select nfrom AS from_id, nto AS to_id, osrmtime AS ttime from node_osrm_data')
    )"
PL/pgSQL function update_routes(text,text) line 38 at EXECUTE statement

The SQL is the following:

-- Empty Tables

delete from containers;
delete from vehicles;

Insert Containers

 INSERT INTO containers(id,x,y,demand) (
    SELECT
    cg.id,
    ST_X(ST_TRANSFORM(cg.geom,4326)),
    ST_Y(ST_TRANSFORM(cg.geom,4326)),
    cast(cg.capacidad as float)
    FROM contenedores_geom cg, sig_municipios s
    WHERE s.municipio='CH' AND cg.cod_recorr='CH_DU_RM_CL_03' AND (cg.nro_serie  LIKE 'CH_03_6%'  OR  cg.nro_serie LIKE 'CH_03_7%' OR  cg.nro_serie LIKE 'CH_03_8%' OR  cg.nro_serie LIKE 'CH_03_9%') AND ST_Intersects(s.geom,cg.geom) 
 );

Insert demand, open and close time. Containers without demand(equals to zero) are set with a demand of 2400.

update containers set open=1320, close=1800, service=1.5, demand=demand_0.15_0.5;

update containers set demand=2400_0.15_0.5 where demand=0;

Insert Vehicles

INSERT INTO vehicles VALUES (1,1000001,1000002,1000001,20.45,10000,1320,1800);

Execute routing function from osrmint with an appropiate name and description to obtain the sequence using VRPTOOLS,
Save the output(route id) in order to use it later.

SELECT new_route('vrptools_cuadrado_SunTueThuMorn2206_s7', 'mC_DU_RM_CL_02-p150-c60-v3-vt20.45-vc10000')

Execute the following function with the same name as the last function in order to obtain the each of the vehicle's route line

SELECT update_routes('vrptools_cuadrado_SunTueThuMorn2206_s7');

**Comment by woodbri** [comment]
@cvvergara I created and pushed command line test case into branch "montevideo-release" for this issue.
`make issue23` will run it. You will need to disable throw-on-assert in baseClasses/vrp_assert.\* to run it in gdb.

**Comment by woodbri** [comment]
This is now fixed in branch montevideo-release-v2
closing.
