### ISSUE TITLE
Postgresql connection lost

### ISSUE THREAD

**Issue by fpacheco** [woodbri/vehicle-routing-problems#26]
We are testing with PostgreSQL 9.3 (Ubuntu 14.04). 

Everything works well with release-v4 (we have tested this branch even with OSRM v4.7.0 without any problem).

When we try to use a newer version of vrptools (montevideo-release or montevideo-release-v2) inside PostgreSQL the connection with de database is lost.

We have found that ./make-test fail but make test-all is Ok (without db connection). That happens with any version of OSRM. 

Thank you. Fernando.

**Comment by woodbri** [comment]
- you need to make sure that baseClasses/vrp_assert.\* has the `#if 0` and NOT `#if 1` so that on error we throw_on_assert so we can catch the error and report it without crashing the database.
- make sure the you do NOT have -DNODEBUG set when you compile otherwise it turns this off and turns off the logging facilities.
- we do not test without OSRM and you must have OSRM running as user postgres to access it from the database, so to run tests from the command line do:

```
sudo -u postgres make test
# OR
make trash
sudo -u postrgres gdb bin/trash
run ../tests/g_du_rm_cl_01
```
- you need to make sure that everything is clean after you upgrade
  - restart the database
  - connect to your database and

```
drop extension vrptools;
create extension vrptools with schema public;
```

```
Now run your tests.
```
- we really need explicit examples of a query that crashes. Emiliano know how to pass us queries that we can reproduce here.
- I just pushed montevideo-release-v2 and added `vehicle-routing-problems/src/trash-prob/trashWithMovingDumps/tests/sql-tests.sql` this is a dump of our `tests` schema and you can fetch the sql to run the tests with `select sql from tests.tests_sql;` after you load the dump file. we run all these tests before we release code to you.

**Comment by fpacheco** [comment]
In this case I used only the tests available in the repository (i don't use my database schema):
1. compile vrptools with the command: ./make-compile. Everything was fine!.
2. run the test (without database) with the command: make test-all.  Everything was fine!.
3. I tried to run the test with databases, that is, standing in the integration directory I ran the command: ./make-test. In this case -at the beginning of the testings- the connection to the database is lost.

I never had that problem in previous versions. The problem appears in versions that are later than 75400752968d92c39ee029f31e746c6d1ed8cb0a (1 Jun 2015).  

I will try again with the latest version. Thank you. Fernando.

**Comment by woodbri** [comment]
I just pushed branch `montevideo-release-v3` with fixes for this issue. We broke the vrp_trashcollectioncheck() with the changes to the optimizer and how trucks and paths of trucks are constructed  in the previous code. Closing, if you find new issues please open a new issue.
