### ISSUE TITLE
Error in delta_time of containers

### ISSUE THREAD

**Issue by etorrano** [woodbri/vehicle-routing-problems#27]
There is an error in the output with some of container's times.

I opened the output in QGIS and I saw this error in its attribute table(on delta_time attribute).

The problem is that the input service time is 1.6 and some of the output times are less than 1.6 and they have to be more than service time plus the distance between the container and the last point of sequence.

![errordeltatime](https://cloud.githubusercontent.com/assets/9082428/8651642/9064d7b4-2950-11e5-957d-a1c556ac6364.jpg)

The query used is the same as C02 test case:

--Empty Tables

delete from containers;
delete from vehicles;

 INSERT INTO containers(id,x,y,demand) (
    SELECT
    cg.id,
    ST_X(ST_TRANSFORM(cg.geom,4326)),
    ST_Y(ST_TRANSFORM(cg.geom,4326)),
    cast(cg.capacidad as float)
    FROM contenedores_geom cg, sig_municipios s
    WHERE s.municipio='C' AND cg.cod_recorr='C_DU_RM_CL_02' AND ST_Intersects(s.geom,cg.geom) AND cg.turno_hora='DOMINGOS, MARTES Y JUEVES CON FERIADOS LABORABLES: Nocturno (22 a 06 hrs.)'

-- Insert demand, open and close time. Containers without demand(equals to zero) are set with a demand of 2400.

update containers set open=360, close=840, service=1.6, demand=demand_0.15_0.45; 
update containers set demand=2400_0.15_0.45 where demand=0;

-- Insert Vehicles

INSERT INTO vehicles VALUES (1,1000001,1000002,1000001,20.45,10000,360,840);

-- Execute routing function from osrmint with an appropiate name and description to obtain the sequence using VRPTOOLS,
-- Save the output(route id) in order to use it later.

SELECT new_route('vrptools_C02_SunTueThuMorn2206_s32', 'mC_DU_RM_CL_02-p150-c50-v3-vt20.45-vc10000')

-- Execute the following function with the same name as the last function in order to obtain the each of the vehicle's route line

SELECT update_routes('vrptools_C02_SunTueThuMorn2206_s32');

**Comment by woodbri** [comment]
@cvvergara I'm looking at this issue and it is not clear what is happening here. Here is my analysis so far:
delta_time is coming from  vehicle_path_t *Solution::getSolutionForPg( UINT &count ) const
http://imaptools.com:8080/docs/vrp-doc/trash-prob_2baseTrash_2solution_8cpp_source.html#l00151
line: 184 is fleet[i][j].deltaTime();
http://imaptools.com:8080/docs/vrp-doc/classTweval.html#a72acbab56fc006aa312d8291cd525066
http://imaptools.com:8080/docs/vrp-doc/tweval_8h_source.html#l00055
which is returning deltaTime_ that gets updated when when void Tweval::evaluate(const Tweval &pred, double cargoLimit) is called
http://imaptools.com:8080/docs/vrp-doc/tweval_8cpp_source.html#l00051

In the results we are seeing lots of values that are less than the service time of 1.6 for the container. The delta_time should be the departure of this node minus the departure of the previous node which can not be less than the service time for this node.

Q: when the code got refactored to deal with trips, are we no longer calling void Tweval::evaluate(const Tweval &pred, double cargoLimit) to maintain the values on nodes? or should I be retrieving these values another way?

**Comment by cvvergara** [comment]
[Reply aid=683379 to=20568786-740291401] Stephen Woodbridge
Try:
http://imaptools.com:8080/docs/vrp-doc/trash-prob_2baseTrash_2solution_8cpp_source.html#l00184
results[seq].deltatime = fleet[i][j].deltaTime();
to
 fleet[i][j].departureTime() -  fleet[i][j-1].departureTime();

about the Q:
getCostOSRM
http://imaptools.com:8080/docs/vrp-doc/costvehicle_8h_source.html#l00137
calls evaluateOsrm
http://imaptools.com:8080/docs/vrp-doc/basevehicle_8cpp_source.html#l00496
which calls
path.evaluate(0, getmaxcapacity());
and evaluates the whole path / truck / trip.

**Comment by cvvergara** [comment]
Probably to make sure its the latest evaluation, call 
getCostOSRM
before getting the results

**Comment by fpacheco** [comment]
In case were useful, I think we also saw this problem in previous versions of vrptools. Many thanks.

**Comment by woodbri** [comment]
getCostOsrm() is already getting called before we call getSolutionForPg(), but just to be sure I added an explicit call just prior to calling getSolutionForPg() and I'm getting the same type of results.

I'll try changing:
results[seq].deltatime = fleet[i][j].deltaTime();
to
results[seq].deltatime = fleet[i][j].departureTime() - fleet[i][j-1].departureTime();

And see if that helps, if it does not then we need to look at why departureTime().

**Comment by woodbri** [comment]
ok, for the record, I can reproduce the same type of bad results, and when I run the same problem from the command line we are getting the correct results. We are looking into why this is happening.

**Comment by cvvergara** [comment]
@etorrano 

Debido a la complejdad de la informción que tienen, yo no me he dedicado a decifar lo que dicen o hacen sus queries para preparar los datos. Asi mismo, seguramente no estoy usando el mismo OSRM ni que ustedes, pero para asegurar que un issue es corregido debidamente, los datos no entrada al menos no deben cambiar. Lo mas probable es que los datos de salida cambien debido a que usamos osrm diferente.

Para evitar que los datos de entrada sean diferentes, les pido por favor crear los archivos:
issue-27.containers.txt
issue-27.dmatrix-time.txt
issue-27.otherlocs.txt
issue-27.vehicles.txt
siguiendo la estructura de los archivos en:
https://github.com/woodbri/vehicle-routing-problems/tree/montevideo-release-v3/src/trash-prob/trashWithMovingDumps/tests

Una vez que los tenga, yo localmente creo una base de datos con esa información solamente, de esa forma me puedo enfocar en la ejecución de ese problema.

Una vez resuelto, ustedes pueden hacer lo mismo, y enfocarse a los datos que enviaron, y comparar  y comentar.

La otra cosa, los screen-shots de resultados me son inútiles. Pueden mandar el shape file, agregarle una columna para comentarios y poner comentarios en unos renglones representativos del problema, o un archivo de excel con comentarios pertinenetes en los renglones pertinentes.
Eso sería de mayor utilidad para mi.

Todo eso se lo pueden mandar por correo a Steve, y el se encarga de transmitirme su información con la que yo puedo trabajar.

@woodbri here is a general translation of what I just transmitted in Spanish

I am sure we are not using the same OSRM version and/or data. So, I will need the following from your part, probably the data you are working with might have changed, so, I want to test at least for a same input. (osrm differences will throw different output)

So for that I would like you to prepare the following files:
issue-27.containers.txt
issue-27.dmatrix-time.txt
issue-27.otherlocs.txt
issue-27.vehicles.txt

from the files I will recreate a small database  and I will have fixed values.

please follow the structure of the files found here:
https://github.com/woodbri/vehicle-routing-problems/tree/montevideo-release-v3/src/trash-prob/trashWithMovingDumps/tests

and instead of giving the screen-shot of the results please create a shapefile that I can use.

**Comment by fpacheco** [comment]
Something that interested me when I first saw the error is that only happens when the service time for the container is a real number. I remember that if the service time is an integer everything works fine.

**Comment by woodbri** [comment]
This issue is fixed in branch montevideo-release-v4, closing.
