### ISSUE TITLE
Figure out how to manage multiple trips to the dump

### ISSUE THREAD

**Issue by woodbri** [woodbri/vehicle-routing-problems#7]
This is a critical issue as it impacts a lot of code and we are not currently setup to do this.
We can just insert a dump node in the path when we reach vehicle capacity:
- what code does this? Automagically in the evaluation code?
- when we move nodes in or out or swap nodes within or between routes we need to re-evaluate where the dumps are placed.
- I have already put code in the neighborhood move generators to check node.isdump() and not move them, but the savings calculations need to take into account if a move forces a dump run or removes a dump run, etc

**Comment by cvvergara** [comment]
As a start, right now the initial solution doesnt include a visit to dump  in the middle of a route
example: (S= staring, D=dump E=ending) 
v1: S 1 2 3 4 5  D  6 7 8 9  D  10 11 12  D  E
Actually as I see it, (and I thought about it before) say you want to schedule trucks from 4:00 am to 11:am
so open(S)=400  closes(E)=1100   will limit the vehicles schedule.
When building the initial solution: we are getting this
S 1 2 3 4 5 D E
we grab another truck and continue...
but what if instead of grabing another truck, we make a path for that same truck where now D is the new starting site, so: (vid is in parenthesis)
v(1): S 1 2 3 4 5  D  6 7 8 9  D  10 11 12  D  E
can be kept as:
V(1.P1)= S 1 2 3 4 5 D D  
V(1.P2)= D 6 7 8 9 D D
V(1.P3)= D 10 11 12 D E
so we use the structure of vehicle to represent the different sections of the path, that way the optimizer can take care of the "subpaths" just as if it was another vheicle.
Therefore with the design Ithinkwe are good, but the initial solution generator should be able to generate "copies of the truck" and whe Vid should be impreved so we can detect what ith section it is, so we can rebuild the path properly.
But this should be handled as another class for vehicle:
class MultiPathVehicle: public Vehicle{...
some functions should be overloaded, etc }
you tell me if this is an idea and I can start working on it

**Comment by woodbri** [comment]
This is an interest idea and it could work. In the example of removing a node from V(1.P1): that would cause all the nodes to shift left, if we make the change in the evaluator I think this would be much cheaper than shifting the nodes around using the tabu search, which would also work. To shift the nodes around in the tabu search, we would have to do something like:
1. for each node move
2. generate the neighborhood of all possible moves
3. apply the best move
4. etc

If we were to do this in the evaluator, or make a "smart evaluator" class that manages adding and deleting dumps in the route. then they just magically appear where needed. and the cost of the route reflects this. Then the surrounding code like the move generators only needs to ignore the dump nodes in the path. This also has the advantage that a vehicle remains a single object and we don't have to mange it as multiple connected objects.
I'm not convinced which is the better option here, but instinct is leaning toward the idea of a "smart evaluator" because of performance and overall simplicity.
Thoughts?

**Comment by woodbri** [comment]
Based on skype discussions, we have decided to use a single vehicle, with multiple dumps. We want the evaluation functions to manage adding/removing/positioning of dumps relative to the nodes in the path. For example any changes to the route needs to review the positions of the dumps in the route and readjust them as appropriate to keep the route feasible and to NOT make extra dump runs when not needed.
